### ISSUE TITLE
Display other types of graphs.

### ISSUE THREAD

**Issue by dblock** [dblock/slack-market#1]
Since https://github.com/dblock/slack-market/commit/712ed155ab3c0d36164375d91eb04dbdf890afe9 we display a default graph. Add something to display all kinds of graphs, like a day graph, month graph, etc.

**Comment by aboutmike** [comment]
This would be a great feature to allow different interval of graphs.

**Comment by ddruker** [comment]
@dblock Does the "default graph" you're referring to in this issue correspond to `charts` in the spec?  I'm going to give this issue a try and I want to make sure that we are on the same page.

**Comment by dblock** [comment]
Yep @ddruker. Looking forward!

**Comment by ddruker** [comment]
Hey @dblock,  Am I allowed to edit quote_spec.rb to account for the new structure of the slack message, which now includes actions (interactive buttons)?  If not, that's OK.

**Comment by ddruker** [comment]
Hey @dblock, are you opposed to me editing the quote_spec.rb in order to account for the newly formatted Slack message, which now includes a `callback_id` and `actions`?

**Comment by dblock** [comment]
@ddruker You should do whatever you think you should do! We can talk around code.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/slack-market/pull/27.
