### ISSUE TITLE
Market Bot

### ISSUE THREAD

**Issue by aboutmike** [dblock/slack-market#11]
Hi - I added the market bot and accidently revoke/remove the bot and trying to re-add it but it seems disable and not working. channel added is stockberrians. was wondering if there's anything you can help or advise? Thanks

**Comment by dblock** [comment]
I think you're hitting https://github.com/dblock/slack-bot-server/issues/10. 

I've disabled the team, try to re-register it again it should work now.

**Comment by aboutmike** [comment]
Thanks dblock for resolving this. Just a thought and want to table the idea and see if it is possible. Is there any ways to customize the included chart so something like intraday or 5 days etc?

**Comment by dblock** [comment]
@aboutmike Everything is possible. Open feature requests here please!
