### ISSUE TITLE
Bought and sold.

### ISSUE THREAD

**Issue by dblock** [dblock/slack-market#4]
We want a (slash) command, eg. `/market bought MSFT` and `/market sold MSFT` as well as /portfolio. This would give you your positions. Then we could keep leaderboards of who's doing well on a daily basis, for example.

**Comment by aboutmike** [comment]
This would be a wonderful feature to have kind of like paper trading.

**Comment by dblock** [comment]
I've implemented something very rudimentary to start, you can do `@market bought MSFT`, `@market sold MSFT` and `@market positions`.

**Comment by aboutmike** [comment]
Thanks, love this. i tested it on the bot, doesnt seem to work though. would be cool to have profit/loss leaderboard :+1:

**Comment by dblock** [comment]
I was still toying with it a few hours ago. What do you see when you (re)try it?

**Comment by dblock** [comment]
Opened https://github.com/dblock/slack-market/issues/20 for leaderboard, please don't hesitate to open new feature requests!
