### ISSUE TITLE
Does not work for foreign markets

### ISSUE THREAD

**Issue by Zygonie** [dblock/slack-market#40]
I've tried with canadian stocks and it does not seem to work. For example, try with tickers:
RY.TO

**Comment by dblock** [comment]
Did you mean to close this? Reopening.

**Comment by Zygonie** [comment]
I mean RY.TO works, the problem I had was with the ticker AKR.TO which is invalid (but was valid) as it is now AKR.V. So the problem is with the ticker on yahoo and not with your bot ! You can close it.
