### ISSUE TITLE
Charts not appearing

### ISSUE THREAD

**Issue by edkimmel** [dblock/slack-market#44]
Recently (last few days) charts stopped appearing in the bot responses. The 1d 1m 1y options are there still. The chart option is not turned off.

New posts have a missing chart block.
Existing posts now have a slack image error.

This may be the result of a change in the yahoo finance api.

http://imgur.com/a/vlTSF

**Comment by dblock** [comment]
Sigh. I'll take a look.

**Comment by dblock** [comment]
Got a confirmation from someone at Yahoo that that API is EOL and won't come back. I replaced Yahoo charts with Google charts for now via https://github.com/dblock/slack-market/commit/19b8321dc1aa8ad2958b39a36575553166807d18.

**Comment by edkimmel** [comment]
RIP Yahoo charts. Thanks for working on this!
