### ISSUE TITLE
999 Request Denied

### ISSUE THREAD

**Issue by edkimmel** [dblock/slack-market#46]
Standard $GOOG requests result in a 999 error. Started happening yesterday, so maybe something with November? Expired key?

<img width="690" alt="screen shot 2017-11-02 at 4 06 56 pm" src="https://user-images.githubusercontent.com/3375008/32347705-e7b3eb06-bfe7-11e7-8c2d-a0a7bf3f4270.png">

**Comment by dblock** [comment]
Sigh. Will take a look soon.

**Comment by dblock** [comment]
https://forums.yahoo.net/t5/Yahoo-Finance-help/http-download-finance-yahoo-com-d-quotes-csv-s-GOOG-amp-f/td-p/387096

**Comment by edkimmel** [comment]
Oof. Guess that api was EOL for yahoo to just shut it down.

**Comment by dblock** [comment]
They never had a date, they said they will shut it down years ago, it just stopped working. I'm working on a replacement.
