### ISSUE TITLE
No charts appearing

### ISSUE THREAD

**Issue by edkimmel** [dblock/slack-market#47]
Hello again, sorry i keep bringing you issues D:

Since the latest google finance update, the bot has not been able to post charts. We don't see anything in the chat except for slackbot's reminder about the market closing.

**Comment by dblock** [comment]
I can confirm that :( Will require quite a bit of work as we need to find a new API, will look into it as soon as I can.

**Comment by dblock** [comment]
I fixed the quotes, but the charts is another story.

**Comment by dblock** [comment]
Charts are back with https://github.com/dblock/slack-market/commit/3477572d47d736afbe60ddcda2b5721218185e26.

**Comment by dblock** [comment]
<img width="582" alt="screen shot 2017-12-02 at 12 34 44 am" src="https://user-images.githubusercontent.com/542335/33512185-b176ba64-d6f8-11e7-9e53-cafd22759997.png">
