### ISSUE TITLE
The property 'extendedChange' is not defined for IEX::Resources::Quote.

### ISSUE THREAD

**Issue by edkimmel** [dblock/slack-market#51]
All commands are returning the error 

> The property 'extendedChange' is not defined for IEX::Resources::Quote.

**Comment by dblock** [comment]
Fixed permanently in https://github.com/dblock/slack-market/commit/84ca9ed88604eafdffe20194cf494c0465e620d8, with forward compatible API changes and deployed.

**Comment by dblock** [comment]
Thanks for reporting this @edkimmel.
