### ISSUE TITLE
Configure to only search for stocks if string starts with $

### ISSUE THREAD

**Issue by lpanger** [dblock/slack-market#74]
I put this plugin into a slack channel and it will search for random strings that people didn't intend to search stocks on. Can we have an option to configure it so that it only searches if the string starts with $?

So if someone types "I like GME" it will do nothing. However "I like $GME" will return stock info.

**Comment by dblock** [comment]
That's done with `set dollars on`, have the team admin DM the bot with that and I think you're all set.
