### ISSUE TITLE
Parse stock symbols with periods properly

### ISSUE THREAD

**Issue by gconcepcion** [dblock/slack-market#9]
Currently if you try to get the quote from any stock symbol that has a "." in the name, it truncates to everything before the "." 

I'm not sure if there are other non [A-Z] characters that may need to be addressed. As far as I'm aware, it's just periods.

**Comment by dblock** [comment]
Do you have an example from Yahoo finance, please?

**Comment by gconcepcion** [comment]
Sorry, forgot to include the example for symbol 
$ROG.VX
http://finance.yahoo.com/q?s=rog.vx&ql=1

In the app, it's reported as 
$ROG
http://finance.yahoo.com/q?s=ROG&ql=1

**Comment by dblock** [comment]
Now fixed.

![screen shot 2016-04-27 at 5 38 44 pm](https://cloud.githubusercontent.com/assets/542335/14869037/ecdbc76e-0c9e-11e6-9782-09faab637390.png)

**Comment by gconcepcion** [comment]
Awesome. Thanks for the quick fix!
